all: FlipCube.class Facelet.class Cubelet.class
	java FlipCube

FlipCube.class: FlipCube.java
	javac FlipCube.java

Facelet.class: Facelet.java
	javac Facelet.java

Face.class: Face.java
	javac Face.java

Cubelet.class: Cubelet.java
	javac Cubelet.java

State.class: State.java
	javac State.java
